version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

sphinx:
  fail_on_warning: false
  builder: html
  configuration: docs/conf.py

python:
  # Install our python package before building the docs
  install:
    - requirements: requirements.txt

formats:
  - pdf
  - epub